### ISSUE TITLE
Add hint for common free times when dragging-and-dropping people into schedules.

### ISSUE THREAD

**Issue by gauravmm** [gauravmm/visigoth#1]
Currently, when dragging person _A_ onto person _B_'s schedule, there is no way to see when _A_ is available. Users have to switch back-and-forth between the two.

Add a UI hint or overlay that indicates _A_'s availability when dropping onto _B_'s schedule.

**Comment by gauravmm** [comment]
Implemented, now testing ahead of deployment.

The green/red regions indicate if the person being dragged is available in the corresponding timeslot.

![tmp-newfeature](https://user-images.githubusercontent.com/445477/47387718-2ebca980-d6de-11e8-9a68-f378efa40a33.png)

**Comment by cyano-cmu** [comment]
That's a great solution, I love it. 👍

**Comment by gauravmm** [comment]
It seems to work.
