### ISSUE TITLE
load hangs

### ISSUE THREAD

**Issue by cyano-cmu** [gauravmm/visigoth#19]
I just re-added my events, and clicked on Load and it just gives me a blank rectangle.
[Visigoth-Scheduler Features.pdf](https://github.com/gauravmm/visigoth/files/2789068/Visigoth-Scheduler.Features.pdf)

I would have gotten this to you a bit earlier, but my dental appointment ran late.

**Comment by gauravmm** [comment]
Turns out this wasn't actually a bug.
