### ISSUE TITLE
missing student from host view

### ISSUE THREAD

**Issue by cyano-cmu** [gauravmm/visigoth#35]
Example case 1: David Woodruff (dwoodruf) schedule, missing 4 students, including 93479

Example case 2: Andy Pavlo (pavlo) schedule, missing 3 students, including 96135

avatar, priority rank, and ID is visible, but name is not, and is not movable and can't click through to the other view.  Also, with second case, the paring DOES exist, but is also listed as not being scheduled at the bottom.  Not sure if this is related to whether there is bilateral requests or not.

**Comment by gauravmm** [comment]
(Edited to remove names)

**Comment by gauravmm** [comment]
Fixed. Simple config error.
