### ISSUE TITLE
Enhancement: Unsaved Data Warning

### ISSUE THREAD

**Issue by tp1l** [gauravmm/visigoth#65]
On the Configuration tab (higher priority) as well as the Events tab and probably other places, it would be nice to have a warning if you try to click off the page without saving your work. I got bitten this morning by not realizing that changes to the config page were not saved until I clicked the "Save" icon and had to redo them all.

**Comment by gauravmm** [comment]
Good suggestion! I'm currently working on this feature.

**Comment by gauravmm** [comment]
Pushed to master. This will be deployed to production later this morning.

**Comment by gauravmm** [comment]
Deployed!
