### ISSUE TITLE
Bug: Alerts page menu is gone

### ISSUE THREAD

**Issue by tp1l** [gauravmm/visigoth#67]
If you click the "Alerts" icon you end up on a blank page with no menu:

<img width="954" alt="visigoth alerts" src="https://user-images.githubusercontent.com/8726443/73661216-b2966d00-4667-11ea-8362-631b748d361a.png">

Hitting the back button will go back to your previous URL but won't recover the menu. Manually refreshing (any URL but .../#alerts) will recover the menu. This happens reliably every time I go to #alerts, and if I jump around enough it has happened twice when going to #config as well, though refreshing that page will work.

**Comment by tp1l** [comment]
As an update, it's happened on other pages as well. I just saw this when going from #scheduler to #people.

To clarify, the alerts page is completely broken, refreshing or not and all I ever see is a blank page there. The other pages that occasionally lose their menu and all other data can be fixed by a browser refresh.

Browser is Google Chrome Version 79.0.3945.130. I have not tried any others.

**Comment by gauravmm** [comment]
Thanks for the detailed description!
Turn out that there are two bugs, one for displaying alerts, and one when moving from page to page.
The former has been fixed in `master` and will be pushed out this morning. I'm working on the latter.

**Comment by gauravmm** [comment]
The latter is fixed in `master`, and will be pushed out in the morning.

**Comment by gauravmm** [comment]
Deployed!
